# Folders returned by the plugin's `.src()` functions. Used while adding tasks to gulp.
src:
  bower:   'assets/bower_components'
  css:     'assets/css'
  favicon: 'assets/favicon'
  icons:   'assets/icons'
  images:  'assets/imgs'
  js:      'assets/js'
  sass:    'assets/scss'

# Folders returned by the plugin's `.dest()` functions. Used inside task functions wich are added to gulp.
dest:
  css:    'public/css'
  fonts:  'public/fonts'
  images: 'public/imgs'
  js:     'public/js'

# The config file to search for in the project root folder.
configFile: 'maelstrom.yml'

# Specify the default mode. This is either `dev` or `prod`.
defaultMode: dev

# Turn information on/off of plugins that are loaded and added tasks.
verbose: true


## JS plugin
js:
  # A list of JS wich will be combined to one file. The output file will be minified and saved to the `dest.js` folder.
  concat: {}
  jshintFile: '%configs%/jshint.yml'

  # jscs: https://github.com/jscs-dev/gulp-jscs
  jscs:
    configPath: '%configs%/jscs.json'

  # jshint: https://github.com/jshint/jshint
  jshint:
    lookup: true
    linter: jshint

  # gulp-uglify: https://github.com/terinjokes/gulp-uglify
  uglify:
    mangle:           true
    preserveComments: some


## CSS plugin
css:
  # A list of CSS files wich will be concatenated to one file. The output file will be autoprefixed, minified and saved to the `dest.css` folder.
  concat: {}

  # gulp-autoprefixer: https://github.com/sindresorhus/gulp-autoprefixer
  autoprefixer:
    cascade:  false
    browsers: ['last 4 version']


## Sass plugin
sass:
  # Specify wich library should be used to compile the Sass files to CSS. Available options are `libsass` (_gulp-sass_) and `ruby` (_gulp-ruby-sass_). All output files will be autoprefixed by default. When the `--dev` flag is not added, the files will also be minified.
  compiler: libsass # libsass|ruby|compass

  # gulp-sass: https://github.com/dlmanning/gulp-sass
  libsass:
    style:          expanded
    sourceComments: true

  # gulp-scss-lint: https://github.com/juanfran/gulp-scss-lint
  scssLint:
    config:     '%configs%/scss-lint.yml'
    bundleExec: false
    verbose:    false


## Images plugin
images:
  # Image file extension wich should be optimized with _gulp-imagemin_.
  types: ['jpg', 'jpeg', 'png', 'gif', 'svg']

  # gulp-imagemin: https://github.com/sindresorhus/gulp-imagemin
  imagemin:
    progressive: true
    interlaced:  true


## Icons plugin
icons:
  # Specify how you would like to use SVG icons. Supported types are `font` or `sprite`. Both options will create a Sass .scss file in a subfolder `maelstrom` in the `src.sass` folder, wich should be imported with `@import` in your main Sass file. Fonts files are written to `dest.fonts`, the sprite file to `dest.images`. Any files with the same name will be overwritten.
  type: font # font|sprite
  # The name as what the output fonts or sprite will be saved.
  outputName: iconfont
  # Name of template to use
  templateFile: '%templates%/iconfont-concrete.js'
  # sass file to @import
  importFile: '%src.bower%/concrete/src/iconfont'

  # gulp-iconfont: https://github.com/nfroidure/gulp-iconfont
  iconfont:
    appendCodepoints:   true
    normalize:          true
    centerHorizontally: true
    fixedWidth:         false
    fontHeight:         100
    fontName:           '%icons.outputName%'


## Default module settings
main:
  # gulp-notify: https://github.com/mikaelbr/gulp-notify
  notify:
    success:

    warning:

    error:
      message: 'Error: <%= error.message %>'
      time:    8000
      wait:    false

  # gulp-size: https://github.com/sindresorhus/gulp-size
  size:
    showFiles: true


# Define all variables wich are used in the config
vars:
  # path to default configs dir
  configs: '%module%/configs'
  # path to templates dir
  templates: '%module%/templates'
